/**
 * Generates docs/harbor/README.md from the catalogue and the recorded evidence.
 *
 * The matrix has exactly one source for each of the three things it shows: capability
 * bounds come from src/lib/registries/harbor-capabilities.ts, proofs from
 * docs/harbor-conformance.json, contract comparisons from docs/harbor-spec-evidence.json. Nothing
 * is typed twice, so nothing can drift.
 *
 * The output is deterministic: it never reads the clock. Age is a display concern, computed by
 * the UI at request time — a generator that aged its own output would make `--check` fail one
 * morning with no commit behind it.
 *
 * Run with: npx tsx scripts/gen-harbor-matrix.ts [--check]
 */
import { readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"

import {
  HARBOR_CAPABILITIES,
  HARBOR_SUPPORT_POLICY,
  capabilityAvailability,
  evaluateCapability,
  parseHarborVersion,
  type ConformanceRun,
  type SpecEvidence,
} from "../src/lib/registries/harbor-capabilities"
import { reconcileSurface } from "../tools/harbor-surface"

const ROOT = resolve(new URL("..", import.meta.url).pathname)
const OUTPUT = resolve(ROOT, "docs/harbor/README.md")
// The digests the application needs to know whether a proof still describes the code it runs.
// Emitted as data because the app cannot import tools/harbor-surface.ts: that module reads the
// source tree through the TypeScript compiler, which has no business in a request path.
const SURFACE_OUTPUT = resolve(ROOT, "docs/harbor-surface.json")

/** Minor versions shown as columns: one below the floor, up to the newest known upstream. */
function displayedMinors(): string[] {
  const floor = parseHarborVersion(HARBOR_SUPPORT_POLICY.floor)!
  const latest = parseHarborVersion(HARBOR_SUPPORT_POLICY.latestKnownMinor)!
  const minors: string[] = []
  for (let minor = floor.minor - 2; minor <= latest.minor; minor++) minors.push(`${latest.major}.${minor}`)
  return minors
}

const GLYPHS: Record<string, string> = {
  verified: "✓",
  expected: "~",
  broken: "✗",
  inconclusive: "!",
  unknown: "?",
  unavailable: "—",
}

function readJson<T>(path: string, key: string): T[] {
  const parsed = JSON.parse(readFileSync(resolve(ROOT, path), "utf8")) as Record<string, unknown>
  return (parsed[key] ?? []) as T[]
}

export function render(): string {
  const runs = readJson<ConformanceRun>("docs/harbor-conformance.json", "runs")
  const specEvidence = readJson<SpecEvidence>("docs/harbor-spec-evidence.json", "comparisons")
  const surface = reconcileSurface(ROOT)
  const surfaceDigests = Object.fromEntries(surface.capabilities.map((entry) => [entry.id, entry.digest]))
  const minors = displayedMinors()
  const out: string[] = []

  out.push("<!-- Generated by scripts/gen-harbor-matrix.ts — do not edit by hand. -->")
  out.push("# Compatibilité Harbor")
  out.push("")
  out.push(
    "Ce que la Gateway sait faire d'un Harbor, version par version, et **sur quelle preuve**.",
    "Trois informations distinctes y sont tenues séparées : ce que Harbor sait faire (disponibilité),",
    "ce sur quoi la Gateway s'engage (support) et ce qui a réellement été exécuté (preuve). Une",
    "version hors support peut porter une fonction opérationnelle ; une version dans la fenêtre",
    "n'est pas vérifiée pour autant.",
  )
  out.push("")

  out.push("## Fenêtre de support")
  out.push("")
  out.push(`- **Plancher déclaré** : ${HARBOR_SUPPORT_POLICY.floor} (*${HARBOR_SUPPORT_POLICY.floorConfidence}*)`)
  if (HARBOR_SUPPORT_POLICY.floorConfidence === "provisional") {
    out.push(
      "  — c'est le plancher que le code applique déjà par sa garde SBOM, pas un plancher mesuré ;",
      "  la première campagne de conformance le confirme ou le déplace.",
    )
  }
  // A declaration, deliberately distinct from the campaigns listed below: what we commit to is a
  // decision, what ran is a measurement, and the two must never be read as one line.
  out.push(
    `- **Versions déclarées prises en charge** : ${
      HARBOR_SUPPORT_POLICY.verifiedVersions.length > 0
        ? HARBOR_SUPPORT_POLICY.verifiedVersions.join(", ")
        : "aucune — engagement pas encore pris (déclaration, pas mesure)"
    }`,
  )
  out.push(`- **Dernière mineure connue en amont** : ${HARBOR_SUPPORT_POLICY.latestKnownMinor}`)

  // Derived from the evidence, never declared: the difference between "a campaign ran" and "we
  // say a campaign ran" is the whole subject of this document.
  const campaigns = new Map<string, { finishedAt: string; verified: number }>()
  for (const run of runs) {
    const capability = HARBOR_CAPABILITIES.find((entry) => entry.id === run.capabilityId)
    if (!capability) continue
    const key = `${run.harborVersion} · ${run.runId}`
    const existing = campaigns.get(key) ?? { finishedAt: run.finishedAt, verified: 0 }
    const passed = new Map(run.tests.map((test) => [test.id, test.result]))
    if (capability.requiredTests.every((id) => passed.get(id) === "pass")) existing.verified += 1
    campaigns.set(key, existing)
  }
  if (campaigns.size > 0) {
    out.push("- **Campagnes exécutées** :")
    for (const [key, campaign] of [...campaigns.entries()].sort()) {
      out.push(
        `  - ${key.split(" · ")[0]} · ${campaign.finishedAt} · ` +
          `${campaign.verified}/${HARBOR_CAPABILITIES.length} capacités vérifiées`,
      )
    }
  }
  out.push("")
  out.push(
    "Hors fenêtre, un Harbor s'ajoute quand même : l'avertissement est affiché, les capacités",
    "indisponibles sont expliquées, et rien n'est refusé au seul motif de la version.",
  )
  out.push("")

  out.push("## Matrice")
  out.push("")
  out.push(`| Capacité | ${minors.join(" | ")} |`)
  out.push(`|---|${minors.map(() => "---").join("|")}|`)
  for (const capability of HARBOR_CAPABILITIES) {
    const cells = minors.map((minor) => {
      const version = parseHarborVersion(minor)!
      if (capabilityAvailability(capability, version) === "unavailable") return GLYPHS.unavailable
      const assessment = evaluateCapability({ capability, version, runs, specEvidence, surfaceDigests })
      return GLYPHS[assessment.proof]
    })
    out.push(`| ${capability.id} | ${cells.join(" | ")} |`)
  }
  out.push("")
  out.push(
    "`✓` vérifié par une exécution sur cette version exacte · `~` attendu (contrat amont inchangé",
    "depuis une version vérifiée, rien n'a tourné) · `✗` en échec, avec le test nommé · `!` non",
    "concluant — une campagne a tourné mais un test requis a été ignoré, faute de scénario ou",
    "d'environnement · `?` non mesuré · `—` la fonction n'existe pas dans cette version.",
  )
  out.push("")
  out.push(
    "Une case porte sur la **mineure**, mais une preuve porte sur une **version exacte et un commit**",
    "de la Gateway : le détail ci-dessous nomme l'un et l'autre. Une réussite sur 2.15.2 ne certifie",
    "ni 2.15.0 ni 2.15.3.",
  )
  out.push("")

  out.push("## Détail par capacité")
  out.push("")
  for (const capability of HARBOR_CAPABILITIES) {
    const own = runs.filter((run) => run.capabilityId === capability.id)
    out.push(`### ${capability.id}`)
    out.push("")
    out.push(
      `- **Borne** : ${capability.since ?? "indéterminée"}${
        capability.removedIn ? `, retirée en ${capability.removedIn}` : ""
      } (*${capability.sinceConfidence}*)`,
    )
    if (capability.sinceConfidence === "disputed") {
      out.push("  — les sources divergent ; la borne conservatrice s'applique tant qu'un test n'a pas tranché.")
    }
    out.push(`- **Repli** : \`${capability.fallback}\``)
    out.push(`- **Opérations** : ${capability.operations.map((operation) => `\`${operation}\``).join(", ")}`)
    out.push(`- **Tests requis** : ${capability.requiredTests.map((test) => `\`${test}\``).join(", ")}`)
    out.push("- **Sources** :")
    for (const evidence of capability.availabilityEvidence) out.push(`  - ${evidence}`)
    if (own.length === 0) {
      out.push("- **Exécutions** : aucune.")
    } else {
      out.push("- **Exécutions** :")
      for (const run of [...own].sort((a, b) => a.finishedAt.localeCompare(b.finishedAt))) {
        out.push(
          `  - ${run.harborVersion} · Gateway \`${run.gatewayCommit}\` · ${run.finishedAt} · ` +
            `${run.tests.filter((test) => test.result === "pass").length}/${capability.requiredTests.length} tests requis`,
        )
      }
    }
    out.push("")
  }

  out.push("## Surface couverte")
  out.push("")
  out.push(
    `Extraite du code par \`tools/harbor-surface.ts\` : **${surface.operations.length} opérations**`,
    `Harbor, toutes rattachées à une capacité. Une opération ajoutée au code sans capacité pour en`,
    "répondre fait échouer `npm run check:harbor-surface`.",
  )
  out.push("")
  // Blank lines are structural in markdown — a table or a paragraph that loses the one before it
  // is swallowed by whatever precedes it. They are placed above; here we only collapse runs.
  return out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n"
}

/** The generated files, so a test can compare against them without spawning this script. */
export const MATRIX_PATH = OUTPUT
export const SURFACE_PATH = SURFACE_OUTPUT

/** The per-capability digests, in the shape docs/harbor-surface.json carries. */
export function renderSurface(): string {
  const surface = reconcileSurface(ROOT)
  return (
    JSON.stringify(
      {
        _note: "Generated by scripts/gen-harbor-matrix.ts — do not edit by hand.",
        operations: surface.operations.length,
        digests: Object.fromEntries(surface.capabilities.map((entry) => [entry.id, entry.digest])),
      },
      null,
      2,
    ) + "\n"
  )
}

if (process.argv[1]?.endsWith("gen-harbor-matrix.ts")) {
  const rendered = render()
  const surface = renderSurface()
  if (process.argv.includes("--check")) {
    const stale = [
      readFileSync(OUTPUT, "utf8") !== rendered ? "docs/harbor/README.md" : null,
      readFileSync(SURFACE_OUTPUT, "utf8") !== surface ? "docs/harbor-surface.json" : null,
    ].filter((entry): entry is string => entry !== null)
    if (stale.length > 0) {
      console.error(`${stale.join(" and ")} out of date — run \`npm run gen:harbor-matrix\` and commit the result.`)
      process.exit(1)
    }
    console.log("docs/harbor/README.md matches the catalogue and the recorded evidence.")
  } else {
    writeFileSync(OUTPUT, rendered)
    writeFileSync(SURFACE_OUTPUT, surface)
    console.log(`Wrote docs/harbor/README.md (${rendered.split("\n").length} lines) and docs/harbor-surface.json.`)
  }
}
