/**
 * Generates the bilingual Harbor README and application surface digests from the
 * capability catalogue, recorded conformance runs and upstream contract evidence.
 * Output is deterministic; display age is computed by the UI at request time.
 * Run with: npm run gen:harbor-matrix (or npm run check:harbor-matrix).
 */
import { readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"

import {
  HARBOR_CAPABILITIES,
  HARBOR_SUPPORT_POLICY,
  capabilityAvailability,
  evaluateCapability,
  parseHarborVersion,
  type ConformanceRun,
  type SpecEvidence,
} from "../src/lib/registries/harbor-capabilities"
import { reconcileSurface } from "../tools/harbor-surface"

const ROOT = resolve(new URL("..", import.meta.url).pathname)
export const MATRIX_PATH = resolve(ROOT, "docs/harbor/README.md")
export const SURFACE_PATH = resolve(ROOT, "docs/harbor-surface.json")

const GLYPHS: Record<string, string> = {
  verified: "✓", expected: "~", broken: "✗", inconclusive: "!", unknown: "?", unavailable: "—",
}

function readJson<T>(path: string, key: string): T[] {
  const parsed = JSON.parse(readFileSync(resolve(ROOT, path), "utf8")) as Record<string, unknown>
  return (parsed[key] ?? []) as T[]
}

export function render(): string {
  const runs = readJson<ConformanceRun>("docs/harbor-conformance.json", "runs")
  const specEvidence = readJson<SpecEvidence>("docs/harbor-spec-evidence.json", "comparisons")
  const surface = reconcileSurface(ROOT)
  const surfaceDigests = Object.fromEntries(surface.capabilities.map((entry) => [entry.id, entry.digest]))
  const floor = parseHarborVersion(HARBOR_SUPPORT_POLICY.floor)!
  const latest = parseHarborVersion(HARBOR_SUPPORT_POLICY.latestKnownMinor)!
  const minors: string[] = []
  for (let minor = floor.minor - 2; minor <= latest.minor; minor++) minors.push(`${latest.major}.${minor}`)

  const campaigns = new Map<string, { finishedAt: string; verified: number }>()
  for (const run of runs) {
    const capability = HARBOR_CAPABILITIES.find((entry) => entry.id === run.capabilityId)
    if (!capability) continue
    const key = `${run.harborVersion} · ${run.runId}`
    const existing = campaigns.get(key) ?? { finishedAt: run.finishedAt, verified: 0 }
    const passed = new Map(run.tests.map((test) => [test.id, test.result]))
    if (capability.requiredTests.every((id) => passed.get(id) === "pass")) existing.verified += 1
    campaigns.set(key, existing)
  }

  const out = [
    "<!-- Generated by scripts/gen-harbor-matrix.ts — do not edit by hand. -->",
    "# Harbor compatibility · Compatibilité Harbor", "",
    "**[English](#english) · [Français](#français)** · [Tessark Gateway](../../README.md)", "",
  ]
  for (const locale of ["en", "fr"] as const) {
    const t = (en: string, fr: string) => locale === "en" ? en : fr
    out.push(t("## English", "## Français"), "")
    out.push(t(
      "This guide distinguishes **availability** (what Harbor provides), **declared support** (the project’s commitment) and **evidence** (what was actually tested). Being inside a declared range does not prove a feature works; being outside it does not by itself disable a registry.",
      "Ce guide distingue la **disponibilité** (ce que Harbor fournit), le **support déclaré** (l’engagement du projet) et les **preuves** (ce qui a réellement été testé). Appartenir à une plage déclarée ne prouve pas qu’une fonctionnalité fonctionne ; être hors plage ne désactive pas un registre à lui seul.",
    ), "")
    out.push(t("### Support window", "### Fenêtre de support"), "")
    out.push(`- **${t("Declared floor", "Plancher déclaré")}**: ${HARBOR_SUPPORT_POLICY.floor} (*${HARBOR_SUPPORT_POLICY.floorConfidence}*)`)
    if (HARBOR_SUPPORT_POLICY.floorConfidence === "provisional") {
      out.push(t(
        "  — based on the existing SBOM guard, not a measured minimum; a conformance campaign must confirm or revise it.",
        "  — fondé sur la garde SBOM existante, pas sur un minimum mesuré ; une campagne de conformance doit le confirmer ou le réviser.",
      ))
    }
    out.push(`- **${t("Declared supported versions", "Versions déclarées prises en charge")}**: ${
      HARBOR_SUPPORT_POLICY.verifiedVersions.length > 0
        ? HARBOR_SUPPORT_POLICY.verifiedVersions.join(", ")
        : t("none — no commitment recorded", "aucune — aucun engagement enregistré")
    }`)
    out.push(`- **${t("Latest upstream minor recorded in the catalogue", "Dernière mineure amont enregistrée dans le catalogue")}**: ${HARBOR_SUPPORT_POLICY.latestKnownMinor}`)
    if (campaigns.size > 0) {
      out.push(`- **${t("Recorded campaigns", "Campagnes enregistrées")}**:`)
      for (const [key, campaign] of [...campaigns.entries()].sort()) {
        out.push(`  - ${key.split(" · ")[0]} · ${campaign.finishedAt} · ${campaign.verified}/${HARBOR_CAPABILITIES.length} ${t("capabilities verified", "capacités vérifiées")}`)
      }
    } else {
      out.push(`- **${t("Recorded campaigns", "Campagnes enregistrées")}**: ${t("none", "aucune")}.`)
    }
    out.push("", t(
      "An out-of-range Harbor can still be added. Gateway displays the warning and explains unavailable capabilities; it does not reject a registry solely because of its version.",
      "Un Harbor hors plage peut toujours être ajouté. Gateway affiche l’avertissement et explique les capacités indisponibles ; il ne refuse pas un registre uniquement à cause de sa version.",
    ), "")

    out.push(t("### Matrix", "### Matrice"), "")
    out.push(`| ${t("Capability", "Capacité")} | ${minors.join(" | ")} |`)
    out.push(`|---|${minors.map(() => "---").join("|")}|`)
    for (const capability of HARBOR_CAPABILITIES) {
      const cells = minors.map((minor) => {
        const version = parseHarborVersion(minor)!
        if (capabilityAvailability(capability, version) === "unavailable") return GLYPHS.unavailable
        return GLYPHS[evaluateCapability({ capability, version, runs, specEvidence, surfaceDigests }).proof]
      })
      out.push(`| ${capability.id} | ${cells.join(" | ")} |`)
    }
    out.push("", t(
      "`✓` verified by a run on that exact version · `~` expected from an unchanged upstream contract since a verified version, without a run · `✗` failed, with a named test · `!` inconclusive because a required scenario/environment was missing · `?` unmeasured · `—` unavailable in that version.",
      "`✓` vérifié par une exécution sur cette version exacte · `~` attendu selon un contrat amont inchangé depuis une version vérifiée, sans exécution · `✗` en échec, avec un test nommé · `!` non concluant faute de scénario/environnement requis · `?` non mesuré · `—` indisponible dans cette version.",
    ), "", t(
      "Columns show minor versions, but evidence applies to an **exact Harbor version and Gateway commit**. Passing on 2.15.2 does not certify 2.15.0 or 2.15.3. Technical identifiers and source-evidence text below are preserved in their original form in both languages.",
      "Les colonnes montrent les versions mineures, mais une preuve concerne une **version Harbor exacte et un commit Gateway**. Une réussite sur 2.15.2 ne certifie ni 2.15.0 ni 2.15.3. Les identifiants techniques et les textes des preuves sources ci-dessous sont conservés dans leur forme originale dans les deux langues.",
    ), "")

    out.push(t("### Capability details", "### Détail par capacité"), "")
    for (const capability of HARBOR_CAPABILITIES) {
      const own = runs.filter((run) => run.capabilityId === capability.id)
      out.push(`#### ${capability.id}`, "")
      const removed = capability.removedIn ? `, ${t("removed in", "retirée en")} ${capability.removedIn}` : ""
      out.push(`- **${t("Available since", "Disponible depuis")}**: ${capability.since ?? t("undetermined", "indéterminé")}${removed} (*${capability.sinceConfidence}*)`)
      if (capability.sinceConfidence === "disputed") {
        out.push(t(
          "  — sources disagree; the conservative bound applies until a test resolves the question.",
          "  — les sources divergent ; la borne conservatrice s’applique tant qu’un test n’a pas tranché.",
        ))
      }
      out.push(`- **${t("Fallback", "Repli")}**: \`${capability.fallback}\``)
      out.push(`- **${t("Operations", "Opérations")}**: ${capability.operations.map((operation) => `\`${operation}\``).join(", ")}`)
      out.push(`- **${t("Required tests", "Tests requis")}**: ${capability.requiredTests.map((test) => `\`${test}\``).join(", ")}`)
      out.push(`- **Sources**:`)
      for (const evidence of capability.availabilityEvidence) out.push(`  - ${evidence.replace(/ \(plan D\d+\)/g, "")}`)
      if (own.length === 0) {
        out.push(`- **${t("Runs", "Exécutions")}**: ${t("none", "aucune")}.`)
      } else {
        out.push(`- **${t("Runs", "Exécutions")}**:`)
        for (const run of [...own].sort((a, b) => a.finishedAt.localeCompare(b.finishedAt))) {
          out.push(`  - ${run.harborVersion} · Gateway \`${run.gatewayCommit}\` · ${run.finishedAt} · ${run.tests.filter((test) => test.result === "pass").length}/${capability.requiredTests.length} ${t("required tests", "tests requis")}`)
        }
      }
      out.push("")
    }
    out.push(t("### Coverage and maintenance", "### Couverture et maintenance"), "")
    out.push(t(
      `The source scanner maps **${surface.operations.length} Harbor operations** to capabilities. An operation added without a capability causes \`npm run check:harbor-surface\` to fail.`,
      `L’analyse du code rattache **${surface.operations.length} opérations Harbor** à des capacités. Une opération ajoutée sans capacité fait échouer \`npm run check:harbor-surface\`.`,
    ), "", t(
      "This README is generated from the [capability catalogue](../../src/lib/registries/harbor-capabilities.ts), [conformance runs](../harbor-conformance.json) and [contract comparisons](../harbor-spec-evidence.json). Update those sources or the [generator](../../scripts/gen-harbor-matrix.ts), then run from the repository root:",
      "Ce README est généré depuis le [catalogue des capacités](../../src/lib/registries/harbor-capabilities.ts), les [exécutions de conformance](../harbor-conformance.json) et les [comparaisons de contrats](../harbor-spec-evidence.json). Modifier ces sources ou le [générateur](../../scripts/gen-harbor-matrix.ts), puis lancer depuis la racine du dépôt :",
    ), "", "```bash", "npm run gen:harbor-matrix", "npm run check:harbor-surface", "npm run check:harbor-matrix", "```", "")
  }
  return out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n"
}

/** Digests consumed by the application without importing the source scanner. */
export function renderSurface(): string {
  const surface = reconcileSurface(ROOT)
  return JSON.stringify({
    _note: "Generated by scripts/gen-harbor-matrix.ts — do not edit by hand.",
    operations: surface.operations.length,
    digests: Object.fromEntries(surface.capabilities.map((entry) => [entry.id, entry.digest])),
  }, null, 2) + "\n"
}

if (process.argv[1]?.endsWith("gen-harbor-matrix.ts")) {
  const outputs = [
    { path: MATRIX_PATH, content: render() },
    { path: SURFACE_PATH, content: renderSurface() },
  ]
  if (process.argv.includes("--check")) {
    const stale = outputs.filter(({ path, content }) => readFileSync(path, "utf8") !== content)
    if (stale.length > 0) {
      console.error(`${stale.map(({ path }) => path).join(" and ")} out of date — run \`npm run gen:harbor-matrix\` and commit the result.`)
      process.exit(1)
    }
    console.log("Harbor README and surface digests match the catalogue and recorded evidence.")
  } else {
    for (const { path, content } of outputs) writeFileSync(path, content)
    console.log("Wrote bilingual Harbor README and surface digests.")
  }
}
